
services:
  conquest-gameserver:
    build: .
    image: mordorwide/dedicated:latest
    container_name: ConquestGameServer
    volumes:
      - ./Dedicated.xml:/home/steamuser/Dedicated.xml:ro
    ports:
      # This port should match the port which is
      # defined in the Dedicated.xml config file.
      - "11900:11900/udp"
    restart: unless-stopped